version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=contactsdb
    command: --skip-password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/contactsdb?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - default

networks:
  default:
