## Stage 1: Build the application with Maven
# Use a base image with Java and Maven installed
FROM maven:3.8.4-openjdk-17-slim AS build

# Set the working directory in the container
WORKDIR /contacts

# Copy the project files to the working directory
COPY pom.xml .
COPY src ./src

# Build the application using Maven
RUN mvn clean package


## Stage 2: Create a lightweight Docker image
# Use a lightweight base image with Java installed
FROM openjdk:17-slim

# Set the working directory in the container
WORKDIR /app

# Copy the built JAR file from the build stage to the container
COPY --from=build /app/target/contacts.jar ./app.jar


# Set the command to run the application
CMD ["java", "-jar", "app.jar"]
